version: "3.7"

services:
  web:
    build:
        context: ./services/web
        dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - model_data:/data/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ./services/celery-queue
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
     - "5555:5555"
    volumes:
      - celery-flower_data:/persistent
    depends_on:
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
  celery-flower_data:
  model_data:
